# Generated by Django 4.1.7 on 2023-03-28 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThermId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plain_name', models.CharField(max_length=30)),
                ('device_mac', models.CharField(max_length=30)),
                ('device_lat', models.IntegerField()),
                ('device_lon', models.IntegerField()),
                ('device_ele', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField()),
                ('ftemp', models.FloatField()),
                ('therm', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dbinterract.thermid')),
            ],
        ),
    ]
